version: "3.9"

services:
  frontend-notes:
    container_name: frontend-notes
    image: frontend-notes
    build: ./frontend-notes
    ports:
      - 8090:8090
    depends_on:
      - backend-notes

  backend-notes:
    container_name: backend-notes
    image: backend-notes
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
