# Utiliza una imagen base de Node.js
FROM node:20-alpine3.18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del frontend al contenedor
COPY package.json .

# Instala las dependencias del frontend
RUN npm install

# Copia los archivos del frontend al contenedor
COPY . .

# Construye la aplicación de producción
RUN npm run build



# Comando para iniciar la aplicación (esto puede variar según tu configuración)
CMD ["npm", "run", "dev"]
